version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.13.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json"}}
      - run:
          name: Install deps
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json"}}
          paths:
            - ./node_modules
      - run:
          name: Lint & Test
          command: npm run lint && npm test && npm run codecov
      - store_artifacts:
          path: test-results.xml
      - store-artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
      - run:
          name: upload to codecov
          command: bash <(curl -s https://codecov.io/bash)